First release

diff --git a/docscleaner_1.0-jammy_amd64/usr/local/bin/docscli b/docscleaner_1.0-jammy_amd64/usr/local/bin/docscli
--- a/docscleaner_1.0-jammy_amd64/usr/local/bin/docscli
+++ b/docscleaner_1.0-jammy_amd64/usr/local/bin/docscli
@@ -6,8 +6,9 @@ touch /home/$USER/docsclean.log
 IFS=$'\n'
 if [ $# -eq 0 ]
   then
-   	echo "docsclean: missing destination path operand"
-   	exit 1
+  	WORK_PATH="/home/$USER/Downloads"
+   	#echo "docsclean: missing destination path operand"
+   	#exit 1
   else
     if [[ ! -d ${!#} ]]; then
         echo "docsclean: cannot stat '${!#}': No such directory"
@@ -29,7 +30,8 @@ IFS=$'\n'
 docx_array=( $(grep -v -e "001.Original_Documents" -e "\/\."  /tmp/docxArray) )
 doc_array=( $(grep -v -e "001.Original_Documents" -e "\/\."  /tmp/docArray) )
 rtf_array=( $(grep -v -e "001.Original_Documents" -e "\/\."  /tmp/rtfArray) )
-readarray -t link_array < /tmp/linkArray
+link_array=( $(grep -v -e "001.Original_Documents"  -e "\/\."  /tmp/linkArray) )
+#readarray -t link_array < /tmp/linkArray
 
 rm -rf /tmp/docxArray
 rm -rf /tmp/docArray
